project_id = "ubrxxvgfbwboucuxteec"

[functions.field-registry-api]
verify_jwt = false

[functions.setup-stripe-products]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.generate-invoice]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-storyboard-job]
verify_jwt = false

[functions.retry-storyboard-job]
verify_jwt = false

[functions.execute-function]
verify_jwt = false

[functions.list-n8n-functions]
verify_jwt = false

[functions.materialize_collections]
verify_jwt = false

[functions.execute-n8n]
verify_jwt = true