import { useLanguage } from '@/contexts/LanguageContext';

const Consent = () => {
  const { t } = useLanguage();

  return (
    <div className="min-h-screen bg-[#0F1320]">
      <main className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl md:text-6xl font-bold text-white mb-8 text-center">
            {t('consentIpPolicy')}
          </h1>
          
          <div className="bg-card rounded-lg p-8 text-foreground">
            <p className="text-lg leading-relaxed mb-6">
              {t('legalPlaceholder')}
            </p>
            
            <div className="space-y-6">
              <section>
                <h2 className="text-2xl font-semibold mb-4">User Content and Consent</h2>
                <p className="text-muted-foreground">
                  By uploading, submitting, or otherwise making available any content through our service, you grant us a non-exclusive, worldwide, royalty-free license to use, modify, and display such content for the purpose of providing our services.
                </p>
              </section>
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">Intellectual Property Rights</h2>
                <p className="text-muted-foreground">
                  You retain ownership of your original content. However, you are responsible for ensuring you have the necessary rights to any content you upload or submit to our service.
                </p>
              </section>
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">AI-Generated Content</h2>
                <p className="text-muted-foreground">
                  Content generated by our AI systems may be based on your input and other data. You acknowledge that AI-generated content may have limitations and should be reviewed before use.
                </p>
              </section>
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">Copyright Compliance</h2>
                <p className="text-muted-foreground">
                  We respect intellectual property rights and expect our users to do the same. If you believe your copyright has been infringed, please contact us with details of the alleged infringement.
                </p>
              </section>
              
              <section>
                <h2 className="text-2xl font-semibold mb-4">Content Removal</h2>
                <p className="text-muted-foreground">
                  We reserve the right to remove any content that violates our terms of service or applicable laws, including content that infringes on intellectual property rights.
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Consent;